version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 8081:80

  backend:
    build:
      context: ./backend
    ports:
      - 4000:3000
    depends_on:
      - postgres  # Указываем зависимость от сервиса postgres
    env_file:
      - ./.env

  postgres:
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data 
    env_file:
      - ./.env
volumes:
  pg-data: